export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_ERROR = 'AUTH_ERROR'

export const FETCH_INFORMATION_REQUEST = 'FETCH_INFORMATION_REQUEST'
export const FETCH_INFORMATION_SUCCESS = 'FETCH_INFORMATION_SUCCESS'
export const FETCH_INFORMATION_ERROR = 'FETCH_INFORMATION_ERROR'